### ISSUE TITLE
Plan to support Laravel 5.6? 

### ISSUE THREAD

**Issue by calvinl** [jrumbut/eloquent-memoize#2]
Been using this package (thank you!) since Laravel 5.1, and we're currently on the upgrade path to 5.6. Would you consider updating it to support 5.6? 

Thanks!

**Comment by jrumbut** [comment]
Glad to hear you are using the package! I would be happy to add 5.6 support myself (probably releasing it around September 3-4) or would accept a pull request that added 5.6 support.

**Comment by calvinl** [comment]
@jrumbut awesome! I'm currently just using a custom branch/repo but if you release it to packagist I'd prefer that.
