### ISSUE TITLE
Conditionally disable memoization?

### ISSUE THREAD

**Issue by calvinl** [jrumbut/eloquent-memoize#5]
Hi!

I've come across a use case in which it would be desirable to temporarily disable memoization (particularly in unit tests where we might expect a value to change to test that it's working properly). 

Is there a way to disable a memoized attribute, or specifically unset it?

**Comment by jrumbut** [comment]
Off the top of my head I think this should do it, let me know if it doesn't that seems like a reasonable feature:

```
Model::disableMemoization();

// do stuff...

Model::enableMemoization();
```

**Comment by jrumbut** [comment]
Hi @calvinl,

Closing and assuming it's working for you, let me know if there are still issues!

Sincerely,
Josh
